Word.find_or_initialize_by(word:'reward').update(audio_url:'R02/R0271400.mp3', part:'noun', definition:"a sum of money offered for the detection or capture of a criminal, the recovery of lost or stolen property, etc.")
Word.find_or_initialize_by(word:'caramel').update(audio_url:'C01/C0127400.mp3', part:'noun', definition:"a liquid made by cooking sugar until it changes color, used for coloring and flavoring food.")
Word.find_or_initialize_by(word:'trademark').update(audio_url:'T04/T0421600.mp3', part:'noun', definition:"any name, symbol, figure, letter, word, or mark adopted and used by a manufacturer or merchant in order to designate his or her goods and to distinguish them from those manufactured or sold by others. A trademark is a proprietary term that is usually registered with the Patent and Trademark Office to assure its exclusive use by its owner.")
Word.find_or_initialize_by(word:'husband').update(audio_url:'H04/H0448400.mp3', part:'noun', definition:"a married man, especially when considered in relation to his partner in marriage.")
Word.find_or_initialize_by(word:'hallway').update(audio_url:'H00/H0042500.mp3', part:'noun', definition:"a corridor, as in a building.")
Word.find_or_initialize_by(word:'brunch').update(audio_url:'B06/B0653000.mp3', part:'noun', definition:"a meal that serves as both breakfast and lunch.")
Word.find_or_initialize_by(word:'splashy').update(audio_url:'S08/S0822600.mp3', part:'adjective', definition:"making a splash or splashes.")
Word.find_or_initialize_by(word:'ping-pong').update(audio_url:'P04/P0465900.mp3', part:'verb (used with object)', definition:"to move back and forth or transfer rapidly from one locale, job, etc., to another; switch: The patient was ping-ponged from one medical specialist to another.")
Word.find_or_initialize_by(word:'obscure').update(audio_url:'O00/O0016300.mp3', part:'adjective', definition:"(of meaning) not clear or plain; ambiguous, vague, or uncertain: an obscure sentence in the contract.")
Word.find_or_initialize_by(word:'length').update(audio_url:'L01/L0177000.mp3', part:'noun', definition:"the longest extent of anything as measured from end to end: the length of a river.")
Word.find_or_initialize_by(word:'canopy').update(audio_url:'C00/C0098700.mp3', part:'noun', definition:"a covering, usually of fabric, supported on poles or suspended above a bed, throne, exalted personage, or sacred object.")
Word.find_or_initialize_by(word:'surefire').update(audio_url:'S11/S1152800.mp3', part:'adjective', definition:"sure to work; foolproof: a surefire moneymaking scheme.")
Word.find_or_initialize_by(word:'passport').update(audio_url:'P01/P0153400.mp3', part:'noun', definition:"an official document issued by the government of a country to one of its citizens and, varying from country to country, authorizing travel to foreign countries and authenticating the bearer's identity, citizenship, right to protection while abroad, and right to reenter his or her native country.")
Word.find_or_initialize_by(word:'habit').update(audio_url:'H00/H0002900.mp3', part:'noun', definition:"an acquired behavior pattern regularly followed until it has become almost involuntary: the habit of looking both ways before crossing the street.")
Word.find_or_initialize_by(word:'quack').update(audio_url:'Q00/Q0005000.mp3', part:'noun', definition:"the harsh, throaty cry of a duck or any similar sound.")
Word.find_or_initialize_by(word:'connect').update(audio_url:'C07/C0762100.mp3', part:'verb (used with object)', definition:"to join, link, or fasten together; unite or bind: to connect the two cities by a bridge; Communication satellites connect the local stations into a network.")
Word.find_or_initialize_by(word:'nurture').update(audio_url:'N02/N0268400.mp3', part:'verb (used with object)', definition:"to feed and protect: to nurture one's offspring.")
Word.find_or_initialize_by(word:'vicinity').update(audio_url:'V01/V0113900.mp3', part:'noun', definition:"the area or region near or about a place; surrounding district; neighborhood: There are no stores in the vicinity of our house.")
Word.find_or_initialize_by(word:'wharf').update(audio_url:'NEW/NEW15995.mp3', part:'noun', definition:"a structure built on the shore of or projecting into a harbor, stream, etc., so that vessels may be moored alongside to load or unload or to lie at rest; quay; pier.")
Word.find_or_initialize_by(word:'eerie').update(audio_url:'E00/E0052200.mp3', part:'adjective', definition:"uncanny, so as to inspire superstitious fear; weird: an eerie midnight howl.")
Word.find_or_initialize_by(word:'mineral').update(audio_url:'M04/M0453800.mp3', part:'noun', definition:"any of a class of substances occurring in nature, usually comprising inorganic substances, as quartz or feldspar, of definite chemical composition and usually of definite crystal structure, but sometimes also including rocks formed by these substances as well as certain natural products of organic origin, as asphalt or coal.")
Word.find_or_initialize_by(word:'aloha').update(audio_url:'A03/A0344200.mp3', part:'noun', definition:'interjection, hello; greetings.')
Word.find_or_initialize_by(word:'coffee').update(audio_url:'C06/C0620300.mp3', part:'noun', definition:"a beverage consisting of a decoction or infusion of the roasted ground or crushed seeds (coffee beans) of the two-seeded fruit (coffee berry) of certain coffee trees.")
Word.find_or_initialize_by(word:'mustang').update(audio_url:'M07/M0708700.mp3', part:'noun', definition:"a small, hardy horse of the American plains, descended from Spanish stock.")
Word.find_or_initialize_by(word:'parade').update(audio_url:'P00/P0089700.mp3', part:'noun', definition:"a large public procession, usually including a marching band and often of a festive nature, held in honor of an anniversary, person, event, etc.")
Word.find_or_initialize_by(word:'lavender').update(audio_url:'L01/L0118500.mp3', part:'noun', definition:"a pale bluish purple.")
Word.find_or_initialize_by(word:'gauze').update(audio_url:'G00/G0076400.mp3', part:'noun', definition:"any thin and often transparent fabric made from any fiber in a plain or leno weave.")
Word.find_or_initialize_by(word:'mirthful').update(audio_url:'M04/M0474900.mp3', part:'adjective', definition:"joyous; gay; jolly: a mirthful laugh.")
Word.find_or_initialize_by(word:'beret').update(audio_url:'B02/B0259300.mp3', part:'noun', definition:"a soft, visorless cap with a close-fitting headband and a wide, round top often with a tab at its center.")
Word.find_or_initialize_by(word:'evaporation').update(audio_url:'E03/E0359500.mp3', part:'noun', definition:"the act or process of evaporating.")
Word.find_or_initialize_by(word:'vigorous').update(audio_url:'V01/V0127500.mp3', part:'adjective', definition:"full of or characterized by vigor: a vigorous effort.")
Word.find_or_initialize_by(word:'boycott').update(audio_url:'B05/B0558000.mp3', part:'verb (used with object)', definition:"to combine in abstaining from, or preventing dealings with, as a means of intimidation or coercion: to boycott a store.")
Word.find_or_initialize_by(word:'impulse').update(audio_url:'I00/I0089500.mp3', part:'noun', definition:"the influence of a particular feeling, mental state, etc.: to act under a generous impulse; to strike out at someone from an angry impulse.")
Word.find_or_initialize_by(word:'winsome').update(audio_url:'W01/W0194200.mp3', part:'adjective', definition:"sweetly or innocently charming; winning; engaging: a winsome smile.")
Word.find_or_initialize_by(word:'alternate').update(audio_url:'A03/A0354400.mp3', part:'verb (used without object)', definition:"to interchange repeatedly and regularly with one another in time or place; rotate (usually followed by with): Day alternates with night.")
Word.find_or_initialize_by(word:'ottoman').update(audio_url:'O02/O0206600.mp3', part:'adjective', definition:"of or relating to the Ottoman Empire.")
Word.find_or_initialize_by(word:'entertain').update(audio_url:'E02/E0212000.mp3', part:'verb (used with object)', definition:"to hold the attention of pleasantly or agreeably; divert; amuse.")
Word.find_or_initialize_by(word:'anorak').update(audio_url:'A05/A0510400.mp3', part:'noun', definition:"a hooded pullover jacket originally made of fur and worn in the arctic, now made of any weather-resistant fabric.")
Word.find_or_initialize_by(word:'documentary').update(audio_url:'D04/D0428200.mp3', part:'adjective', definition:"Also, documental documents: a documentary history of France.")
Word.find_or_initialize_by(word:'jargon').update(audio_url:'J00/J0028600.mp3', part:'noun', definition:"the language, especially the vocabulary, peculiar to a particular trade, profession, or group: medical jargon.")
Word.find_or_initialize_by(word:'kiwi').update(audio_url:'K01/K0134100.mp3', part:'noun', definition:"any of several flightless, ratite birds of the genus Apteryx, of New Zealand, allied to the extinct moas.")
Word.find_or_initialize_by(word:'eyebrow').update(audio_url:'E04/E0443100.mp3', part:'noun', definition:"the arch or ridge forming the upper part of the orbit of the eye.")
Word.find_or_initialize_by(word:'velcro').update(audio_url:'V00/V0061100.mp3', part:'noun', definition:"a brand of fastening tape consisting of opposing pieces of fabric, one with a dense arrangement of tiny nylon hooks and the other with a dense nylon pile, that interlock when pressed together, used as a closure on garments, luggage, etc., in place of buttons, zippers, and the like.")
Word.find_or_initialize_by(word:'random').update(audio_url:'R00/R0056000.mp3', part:'adjective', definition:"proceeding, made, or occurring without definite aim, reason, or pattern: the random selection of numbers.")
Word.find_or_initialize_by(word:'summary').update(audio_url:'S11/S1106500.mp3', part:'noun', definition:"a comprehensive and usually brief abstract, recapitulation, or compendium of previously stated facts or statements.")
Word.find_or_initialize_by(word:'macaw').update(audio_url:'M00/M0004300.mp3', part:'noun', definition:"any of various large, long-tailed parrots, chiefly of the genus Ara, of tropical and subtropical America, noted for their brilliant plumage and harsh voice.")
Word.find_or_initialize_by(word:'variety').update(audio_url:'V00/V0038500.mp3', part:'noun', definition:"the state of being varied or diversified: to give variety to a diet.")
Word.find_or_initialize_by(word:'moxie').update(audio_url:'M06/M0650800.mp3', part:'noun', definition:"force of character, determination, or nerve: when you've got moxie, you need the clothes to match")
Word.find_or_initialize_by(word:'jersey').update(audio_url:'J00/J0051000.mp3', part:'noun', definition:'a close-fitting, knitted sweater or shirt.')
Word.find_or_initialize_by(word:'people').update(audio_url:'P02/P0250900.mp3', part:'noun', definition:'persons indefinitely or collectively')
Word.find_or_initialize_by(word:'cough').update(audio_url:'C08/C0898800.mp3', part:'verb (used without object)', definition:'to expel air from the lungs suddenly with a harsh noise, often involuntarily.')
Word.find_or_initialize_by(word:'marlin').update(audio_url:'M01/M0163500.mp3', part:'noun', definition:'any large, saltwater game fish of the genera Makaira and Tetrapterus, having the upper jaw elongated into a spearlike structure.')
Word.find_or_initialize_by(word:'warning').update(audio_url:'W00/W0041700.mp3', part:'noun', definition:'the act or utterance of one who warns or the existence, appearance, sound, etc., of a thing that warns.')
Word.find_or_initialize_by(word:'sonar').update(audio_url:'S07/S0718900.mp3', part:'noun', definition:'a method for detecting and locating objects submerged in water by echolocation.')
Word.find_or_initialize_by(word:'forum').update(audio_url:'F03/F0316200.mp3', part:'noun', definition:'the marketplace or public square of an ancient Roman city, the center of judicial and business affairs and a place of assembly for the people.')
Word.find_or_initialize_by(word:'silent').update(audio_url:'S05/S0523800.mp3', part:'adjective', definition:'making no sound; quiet; still: a silent motor.')
Word.find_or_initialize_by(word:'domino').update(audio_url:'D04/D0453100.mp3', part:'noun', definition:'a flat, thumbsized, rectangular block, the face of which is divided into two parts, each either blank or bearing from one to six pips or dots: 28 such pieces form a complete set.')
Word.find_or_initialize_by(word:'glance').update(audio_url:'G01/G0177500.mp3', part:'verb (used without object)', definition:'to look quickly or briefly.')
Word.find_or_initialize_by(word:'atomic').update(audio_url:'A07/A0785700.mp3', part:'adjective', definition:'of, pertaining to, resulting from, or using atoms, atomic energy, or atomic bombs: an atomic explosion.')
Word.find_or_initialize_by(word:'native').update(audio_url:'N00/N0038500.mp3', part:'adjective', definition:"being the place or environment in which a person was born or a thing came into being: one's native land.")
Word.find_or_initialize_by(word:'clutch').update(audio_url:'C05/C0582400.mp3', part:'verb (used with object)', definition:'to seize with or as with the hands or claws; snatch: The bird swooped down and clutched its prey with its claws.')
Word.find_or_initialize_by(word:'polar').update(audio_url:'P05/P0586100.mp3', part:'adjective', definition:'of or relating to the North or South Pole.')
Word.find_or_initialize_by(word:'field').update(audio_url:'F01/F0126400.mp3', part:'noun', definition:'an expanse of open or cleared ground, especially a piece of land suitable or used for pasture or tillage.')
Word.find_or_initialize_by(word:'ocean').update(audio_url:'O00/O0026100.mp3', part:'noun', definition:"the vast body of salt water that covers almost three fourths of the earth's surface.")
Word.find_or_initialize_by(word:'acre').update(audio_url:'A00/A0095400.mp3', part:'noun', definition:'a common measure of area: in the U.S. and U.K., 1 acre equals 4,840 square yards (4,047 square meters) or 0.405 hectare; 640 acres equals one square mile.')
Word.find_or_initialize_by(word:'gratis').update(audio_url:'G03/G0314700.mp3', part:'adverb', definition:"without charge or payment; free: The manufacturer provided an extra set of coat buttons gratis.")
Word.find_or_initialize_by(word:'sympathy').update(audio_url:'S12/S1207500.mp3', part:'noun', definition:"harmony of or agreement in feeling, as between persons or on the part of one person with respect to another.")
Word.find_or_initialize_by(word:'paragon').update(audio_url:'P00/P0093300.mp3', part:'noun', definition:"a model or pattern of excellence or of a particular excellence: a paragon of virtue.")
Word.find_or_initialize_by(word:'festooned').update(audio_url:'F01/F0106900.mp3', part:'noun', definition:"a string or chain of flowers, foliage, ribbon, etc., suspended in a curve between two points.")
Word.find_or_initialize_by(word:'tonsils').update(audio_url:'T03/T0364300.mp3', part:'noun', definition:"a prominent oval mass of lymphoid tissue on each side of the throat.")
Word.find_or_initialize_by(word:'mogul').update(audio_url:'M05/M0526700.mp3', part:'noun', definition:"a bump or mound of hard snow on a ski slope.")
Word.find_or_initialize_by(word:'frequently').update(audio_url:'F03/F0368500.mp3', part:'adverb', definition:"often; many times; at short intervals.")
Word.find_or_initialize_by(word:'pomposity').update(audio_url:'P06/P0629800.mp3', part:'noun', definition:"the quality of being pompous.")
Word.find_or_initialize_by(word:'marathon').update(audio_url:'M01/M0135400.mp3', part:'noun', definition:"a foot race over a course measuring 26 mi. 385 yards (42 km 195 meters).")
Word.find_or_initialize_by(word:'polemic').update(audio_url:'P05/P0588800.mp3', part:'noun', definition:"a controversial argument, as one against some opinion, doctrine, etc.")
Word.find_or_initialize_by(word:'euro').update(audio_url:'E03/E0348100.mp3', part:'noun', definition:"the single European currency, which replaced the national currencies of France, Germany, Spain, Italy, Greece, Portugal, Luxembourg, Austria, Finland, the Republic of Ireland, Belgium, and the Netherlands in 2002. Seventeen member states of the European Union now use the euro.")
Word.find_or_initialize_by(word:'wrinkle').update(audio_url:'W02/W0253100.mp3', part:'noun', definition:'a small furrow or crease in the skin, especially of the face, as from aging or frowning.')
Word.find_or_initialize_by(word:'flattery').update(audio_url:'F02/F0201400.mp3', part:'noun', definition:"excessive and insincere praise, especially that given to further one's own interests. his healthy distrust of courtiers' flattery. synonyms:	praise, adulation, compliments, blandishments, honeyed words.")
Word.find_or_initialize_by(word:'blossom').update(audio_url:'B04/B0426500.mp3', part:'noun', definition:'the flower of a plant, especially of one producing an edible fruit.')
Word.find_or_initialize_by(word:'magma').update(audio_url:'M00/M0040300.mp3', part:'noun', definition:"Geology. molten material beneath or within the earth's crust, from which igneous rock is formed.")
Word.find_or_initialize_by(word:'galaxy').update(audio_url:'G00/G0017200.mp3', part:'noun', definition:"Astronomy. a large system of stars held together by mutual gravitation and isolated from similar systems by vast regions of space.")
Word.find_or_initialize_by(word:'catalog').update(audio_url:'C02/C0205000.mp3', part:'noun', definition:'a list or record, as of items for sale or courses at a university, systematically arranged and often including descriptive material: a stamp catalog.')
Word.find_or_initialize_by(word:'lactose').update(audio_url:'L00/L0019100.mp3', part:'noun', definition:'Biochemistry. a disaccharide, C <sub>12</sub> H <sub>22</sub> O <sub>11</sub> , present in milk, that upon hydrolysis yields glucose and galactose.')
Word.find_or_initialize_by(word:'diploma').update(audio_url:'D03/D0330100.mp3', part:'noun', definition:'a document given by an educational institution conferring a degree on a person or certifying that the person has satisfactorily completed a course of study.')
Word.find_or_initialize_by(word:'emerald').update(audio_url:'E01/E0137800.mp3', part:'noun', definition:'a rare variety of beryl that is colored green by chromium and valued as a gem.')
Word.find_or_initialize_by(word:'atrium').update(audio_url:'A07/A0789400.mp3', part:'noun', definition:"Architecture. Also called cavaedium. the main or central room of an ancient Roman house, open to the sky at the center and usually having a pool for the collection of rain water.")
Word.find_or_initialize_by(word:'whiff').update(audio_url:'NEW/NEW16095.mp3', part:'noun', definition:'a slight gust or puff of wind, air, vapor, smoke, or the like: a whiff of fresh air.')
Word.find_or_initialize_by(word:'phrasing').update(audio_url:'P04/P0402500.mp3', part:'noun', definition:'the act of forming phrases.')
Word.find_or_initialize_by(word:'cyberspace').update(audio_url:'C10/C1082700.mp3', part:'noun', definition:'the realm of electronic communication.')
Word.find_or_initialize_by(word:'mutiny').update(audio_url:'M07/M0712800.mp3', part:'noun', definition:'revolt or rebellion against constituted authority, especially by sailors against their officers.')
Word.find_or_initialize_by(word:'origin').update(audio_url:'O01/O0158700.mp3', part:'noun', definition:'something from which anything arises or is derived; source; fountainhead: to follow a stream to its origin.')
Word.find_or_initialize_by(word:'parable').update(audio_url:'P00/P0087100.mp3', part:'noun', definition:'a short allegorical story designed to illustrate or teach some truth, religious principle, or moral lesson.')
Word.find_or_initialize_by(word:'chemistry').update(audio_url:'C03/C0366800.mp3', part:'noun', definition:'the science that deals with the composition and properties of substances and various elementary forms of matter.')
Word.find_or_initialize_by(word:'swollen').update(audio_url:'S11/S1195200.mp3', part:'verb', definition:'a past participle of swell. (especially of a part of the body) become larger or rounder in size, typically as a result of an accumulation of fluid.')
Word.find_or_initialize_by(word:'diagonal').update(audio_url:'D02/D0258400.mp3', part:'adjective', definition:'Mathematics. connecting two nonadjacent angles or vertices of a polygon or polyhedron, as a straight line.')
Word.find_or_initialize_by(word:'personnel').update(audio_url:'P03/P0306700.mp3', part:'noun', definition:"a body of persons employed in an organization or place of work.")
Word.find_or_initialize_by(word:'tapioca').update(audio_url:'T00/T0060800.mp3', part:'noun', definition:"a food substance prepared from cassava in granular, flake, pellet (pearl tapioca) or flour form, used in puddings, as a thickener, etc.")
Word.find_or_initialize_by(word:'electrode').update(audio_url:'E00/E0088500.mp3', part:'noun', definition:"a conductor, not necessarily metallic, through which a current enters or leaves a nonmetallic medium, as an electrolytic cell, arc generator, vacuum tube, or gaseous discharge tube.")
Word.find_or_initialize_by(word:'modular').update(audio_url:'M05/M0523000.mp3', part:'adjective', definition:"of or relating to a module or a modulus.")
Word.find_or_initialize_by(word:'quagmire').update(audio_url:'Q00/Q0014600.mp3', part:'noun', definition:"an area of miry or boggy ground whose surface yields under the tread; a bog.")
Word.find_or_initialize_by(word:'fulfill').update(audio_url:'F04/F0407400.mp3', part:'verb (used with object)', definition:"making someone satisfied or happy because of fully developing their character or abilities: a fulfilling and rewarding career")
Word.find_or_initialize_by(word:'hammock').update(audio_url:'H00/H0054400.mp3', part:'noun', definition:'a hanging bed or couch made of canvas, netted cord, or the like, with cords attached to supports at each end.')
Word.find_or_initialize_by(word:'magma').update(audio_url:'M00/M0040300.mp3', part:'noun', definition:"Geology. molten material beneath or within the earth's crust, from which igneous rock is formed.")
Word.find_or_initialize_by(word:'everglades').update(audio_url:'E03/E0364100.mp3', part:'noun', definition:'a swampy and partly forested region in S Florida, mostly S of Lake Okeechobee. Over 5000 sq. mi. (12,950 sq. km).')
Word.find_or_initialize_by(word:'snippet').update(audio_url:'S06/S0663800.mp3', part:'noun', definition:'a small piece snipped off; a small bit, scrap, or fragment: an anthology of snippets.')
Word.find_or_initialize_by(word:'grumble').update(audio_url:'G03/G0372300.mp3', part:'verb (used without object)', definition:'to murmur or mutter in discontent; complain sullenly.')
Word.find_or_initialize_by(word:'granola').update(audio_url:'G03/G0303400.mp3', part:'noun', definition:'a breakfast food consisting of rolled oats, brown sugar, nuts, dried fruit, etc., usually served with milk.')
Word.find_or_initialize_by(word:'umpire').update(audio_url:'U00/U0023200.mp3', part:'noun', definition:'a person selected to rule on the plays in a game.')
Word.find_or_initialize_by(word:'americana').update(audio_url:'A03/A0386300.mp3', part:'noun', definition:'(often used with a plural verb) books, papers, maps, etc., relating to America, especially to its history, culture, and geography.')
Word.find_or_initialize_by(word:'nimble').update(audio_url:'N01/N0146500.mp3', part:'adjective', definition:'quick and light in movement; moving with ease; agile; active; rapid: nimble feet.')
Word.find_or_initialize_by(word:'trinket').update(audio_url:'T05/T0503200.mp3', part:'noun', definition:'a small ornament, piece of jewelry, etc., usually of little value.')
Word.find_or_initialize_by(word:'pedigree').update(audio_url:'P02/P0206900.mp3', part:'noun', definition:'an ancestral line; line of descent; lineage; ancestry.')
Word.find_or_initialize_by(word:'hubbub').update(audio_url:'H04/H0420100.mp3', part:'noun', definition:'a loud, confused noise, as of many voices: There was quite a hubbub in the auditorium after the announcement.')
Word.find_or_initialize_by(word:'several').update(audio_url:'S03/S0383400.mp3', part:'adjective', definition:'being more than two but fewer than many in number or kind: several ways of doing it.')
Word.find_or_initialize_by(word:'torrent').update(audio_url:'T03/T0385500.mp3', part:'noun', definition:'a stream of water flowing with great rapidity and violence.')
Word.find_or_initialize_by(word:'announcer').update(audio_url:'A05/A0504000.mp3', part:'noun', definition:'a person who announces, especially one who introduces programs, presents news items, reads advertisements, and does other similar assignments over radio or television.')
Word.find_or_initialize_by(word:'beverage').update(audio_url:'B02/B0288900.mp3', part:'noun', definition:'any potable liquid, especially one other than water, as tea, coffee, beer, or milk: The price of the meal includes a beverage.')
Word.find_or_initialize_by(word:'waist').update(audio_url:'W00/W0011400.mp3', part:'noun', definition:'the part of the body in humans between the ribs and the hips, usually the narrowest part of the torso.')
Word.find_or_initialize_by(word:'valiant').update(audio_url:'V00/V0015000.mp3', part:'adjective', definition:'boldly courageous; brave; stout-hearted: a valiant soldier.')
Word.find_or_initialize_by(word:'thigh').update(audio_url:'T02/T0232500.mp3', part:'noun', definition:'the part of the lower limb in humans between the hip and the knee.')
Word.find_or_initialize_by(word:'truce').update(audio_url:'T05/T0536000.mp3', part:'noun', definition:'a suspension of hostilities for a specified period of time by mutual agreement of the warring parties; cease-fire; armistice.')
Word.find_or_initialize_by(word:'masterpiece').update(audio_url:'M01/M0195600.mp3', part:'noun', definition:"a person's greatest piece of work, as in an art.")
Word.find_or_initialize_by(word:'nonfiction').update(audio_url:'N01/N0194800.mp3', part:'noun', definition:'the branch of literature comprising works of narrative prose dealing with or offering opinions or conjectures upon facts and reality, including biography, history, and the essay (opposed to fiction and distinguished from poetry and drama).')
Word.find_or_initialize_by(word:'platoon').update(audio_url:'P05/P0530100.mp3', part:'noun', definition:'a military unit consisting of two or more squads or sections and a headquarters.')
Word.find_or_initialize_by(word:'eleemosynary').update(audio_url:'E01/E0100500.mp3', part:'adjective', definition:"")
Word.find_or_initialize_by(word:'junior').update(audio_url:'J01/J0114600.mp3', part:'adjective', definition:'younger (designating the younger of two men bearing the same full name, as a son named after his father; often written as Jr. or jr. following the name): May I speak with the junior Mr. Hansen?')
Word.find_or_initialize_by(word:'kangaroo').update(audio_url:'K00/K0020600.mp3', part:'noun', definition:'any herbivorous marsupial of the family Macropodidae, of Australia and adjacent islands, having a small head, short forelimbs, powerful hind legs used for leaping, and a long, thick tail: several species are threatened or endangered.')
Word.find_or_initialize_by(word:'excuse').update(audio_url:'E03/E0387400.mp3', part:'verb (used with object)', definition:'to regard or judge with forgiveness or indulgence; pardon or forgive; overlook (a fault, error, etc.): Excuse his bad manners.')
Word.find_or_initialize_by(word:'astronaut').update(audio_url:'A07/A0767700.mp3', part:'noun', definition:'a person engaged in or trained for spaceflight.')
Word.find_or_initialize_by(word:'lyrics').update(audio_url:'L04/L0458200.mp3', part:'adjective', definition:"(of poetry) having the form and musical quality of a song, and especially the character of a songlike outpouring of the poet's own thoughts and feelings, as distinguished from epic and dramatic poetry.")
Word.find_or_initialize_by(word:'breadwinner').update(audio_url:'B05/B0592200.mp3', part:'noun', definition:'a person who earns a livelihood, especially one who also supports dependents.')
Word.find_or_initialize_by(word:'worrywart').update(audio_url:'W02/W0243400.mp3', part:'noun', definition:'a person who tends to worry habitually and often needlessly; pessimist; fussbudget.')
Word.find_or_initialize_by(word:'cymbals').update(audio_url:'C10/C1093500.mp3', part:'noun', definition:'a concave plate of brass or bronze that produces a sharp, ringing sound when struck: played either in pairs, by being struck together, or singly, by being struck with a drumstick or the like.')
Word.find_or_initialize_by(word:'dispel').update(audio_url:'D03/D0377600.mp3', part:'verb (used with object)', definition:'to drive off in various directions; disperse; dissipate: to dispel the dense fog.')
Word.find_or_initialize_by(word:'phrasing').update(audio_url:'P04/P0402500.mp3', part:'noun', definition:'the act of forming phrases.')
Word.find_or_initialize_by(word:'dwindled').update(audio_url:'D06/D0601200.mp3', part:'verb (used without object)', definition:'to become smaller and smaller; shrink; waste away: His vast fortune has dwindled away.')
Word.find_or_initialize_by(word:'soprano').update(audio_url:'S07/S0730300.mp3', part:'noun', definition:"the uppermost part or voice.")
Word.find_or_initialize_by(word:'tropical').update(audio_url:'T05/T0528800.mp3', part:'adjective', definition:"pertaining to, characteristic of, occurring in, or inhabiting the tropics, especially the humid tropics: tropical flowers.")
Word.find_or_initialize_by(word:'tarnish').update(audio_url:'T00/T0068500.mp3', part:'verb (used with object)', definition:"to dull the luster of (a metallic surface) especially by oxidation; discolor.")
Word.find_or_initialize_by(word:'fondant').update(audio_url:'F02/F0265800.mp3', part:'noun', definition:"a thick, creamy sugar paste, the basis of many candies.")
Word.find_or_initialize_by(word:'cyberspace').update(audio_url:'C10/C1082700.mp3', part:'noun', definition:"the realm of electronic communication.")
Word.find_or_initialize_by(word:'prowess').update(audio_url:'P08/P0873700.mp3', part:'noun', definition:"exceptional valor, bravery, or ability, especially in combat or battle.")
Word.find_or_initialize_by(word:'measly').update(audio_url:'M02/M0245600.mp3', part:'adjective', definition:"Informal. contemptibly small, meager, or slight: They paid me a measly fifteen dollars for a day's work. wretchedly bad or unsatisfactory: a measly performance.")
Word.find_or_initialize_by(word:'trellis').update(audio_url:'T04/T0463700.mp3', part:'noun', definition:"a frame or structure of latticework; lattice.")
Word.find_or_initialize_by(word:'autumn').update(audio_url:'A08/A0841600.mp3', part:'noun', definition:"the season between summer and winter; fall. In the Northern Hemisphere it is from the September equinox to the December solstice; in the Southern Hemisphere it is from the March equinox to the June solstice.")
Word.find_or_initialize_by(word:'variety').update(audio_url:'V00/V0038500.mp3', part:'noun', definition:"the state of being varied or diversified: to give variety to a diet.")
Word.find_or_initialize_by(word:'parable').update(audio_url:'P00/P0087100.mp3', part:'noun', definition:"a short allegorical story designed to illustrate or teach some truth, religious principle, or moral lesson.")
Word.find_or_initialize_by(word:'splurge').update(audio_url:'S08/S0827500.mp3', part:'verb (used without object)', definition:"to indulge oneself in some luxury or pleasure, especially a costly one: They splurged on a trip to Europe.")
Word.find_or_initialize_by(word:'balderdash').update(audio_url:'B00/B0051600.mp3', part:'noun', definition:"senseless, stupid, or exaggerated talk or writing; nonsense.")
Word.find_or_initialize_by(word:'hodgepodge').update(audio_url:'H03/H0317000.mp3', part:'noun', definition:"a heterogeneous mixture; jumble.")
Word.find_or_initialize_by(word:'superlative').update(audio_url:'S11/S1132500.mp3', part:'adjective', definition:"of the highest kind, quality, or order; surpassing all else or others; supreme; extreme: superlative wisdom.")
Word.find_or_initialize_by(word:'victorian').update(audio_url:'V01/V0116300.mp3', part:'adjective', definition:"of or relating to Queen Victoria or the period of her reign: Victorian poets.")
Word.find_or_initialize_by(word:'columnist').update(audio_url:'C06/C0667200.mp3', part:'noun', definition:"the writer or editor of a newspaper or magazine column.")
Word.find_or_initialize_by(word:'bewilder').update(audio_url:'B02/B0290000.mp3', part:'verb (used with object)', definition:"to confuse or puzzle completely; perplex: These shifting attitudes bewilder me.")
Word.find_or_initialize_by(word:'hammock').update(audio_url:'H00/H0054400.mp3', part:'noun', definition:"a hanging bed or couch made of canvas, netted cord, or the like, with cords attached to supports at each end.")
Word.find_or_initialize_by(word:'squander').update(audio_url:'S08/S0857200.mp3', part:'verb (used with object)', definition:"to spend or use (money, time, etc.) extravagantly or wastefully (often followed by away).")
Word.find_or_initialize_by(word:'curfew').update(audio_url:'C10/C1055100.mp3', part:'noun', definition:"an order establishing a specific time in the evening after which certain regulations apply, especially that no civilians or other specified group of unauthorized persons may be outdoors or that places of public assembly must be closed.")
Word.find_or_initialize_by(word:'absurd').update(audio_url:'A00/A0041700.mp3', part:'adjective', definition:"utterly or obviously senseless, illogical, or untrue; contrary to all reason or common sense; laughably foolish or false: an absurd explanation.")
Word.find_or_initialize_by(word:'hoity-toity').update(audio_url:'H03/H0324200.mp3', part:'adjective', definition:"assuming airs; pretentious; haughty.")
Word.find_or_initialize_by(word:'whiff').update(audio_url:'NEW/NEW16095.mp3', part:'noun', definition:"a slight gust or puff of wind, air, vapor, smoke, or the like: a whiff of fresh air.")
Word.find_or_initialize_by(word:'fundamental').update(audio_url:'F04/F0417500.mp3', part:'adjective', definition:"serving as, or being an essential part of, a foundation or basis; basic; underlying: fundamental principles; the fundamental structure.")
Word.find_or_initialize_by(word:'approximate').update(audio_url:'A06/A0619000.mp3', part:'adjective', definition:"near or approaching a certain state, condition, goal, or standard.")
Word.find_or_initialize_by(word:'infrastructure').update(audio_url:'I01/I0166800.mp3', part:'noun', definition:"the basic, underlying framework or features of a system or organization.")
Word.find_or_initialize_by(word:'commodious').update(audio_url:'C06/C0686300.mp3', part:'adjective', definition:"spacious and convenient; roomy: a commodious apartment.")
Word.find_or_initialize_by(word:'machination').update(audio_url:'M00/M0009800.mp3', part:'noun', definition:"an act or instance of machinating.")
Word.find_or_initialize_by(word:'ramification').update(audio_url:'R00/R0048800.mp3', part:'noun', definition:"the act or process of ramifying.")
Word.find_or_initialize_by(word:'schnitzel').update(audio_url:'S01/S0179900.mp3', part:'noun', definition:"a cutlet, especially of veal.")
Word.find_or_initialize_by(word:'susurration').update(audio_url:'S11/S1167000.mp3', part:'noun', definition:"a soft murmur; whisper.")
Word.find_or_initialize_by(word:'ecclesiastical').update(audio_url:'E00/E0020600.mp3', part:'adjective', definition:"of or relating to the church or the clergy; churchly; clerical; not secular.")
Word.find_or_initialize_by(word:'insouciance').update(audio_url:'I02/I0206800.mp3', part:'noun', definition:"the quality of being insouciant; lack of care or concern; indifference.")
Word.find_or_initialize_by(word:'cheongsam').update(audio_url:'C03/C0372900.mp3', part:'noun', definition:"a form-fitting, knee-length dress with a mandarin collar and slit skirt, worn chiefly by Chinese women.")
Word.find_or_initialize_by(word:'eleemosynary').update(audio_url:'E01/E0100500.mp3', part:'adjective', definition:"of or relating to alms, charity, or charitable donations; charitable.")
Word.find_or_initialize_by(word:'Iroquois').update(audio_url:'I03/I0305400.mp3', part:'noun', definition:"a member of a North American Indian confederacy, the Five Nations, comprising the Mohawks, Oneidas, Onondagas, Cayugas, and Senecas, and later the Tuscaroras.")
Word.find_or_initialize_by(word:'tractor').update(audio_url:'T04/T0420800.mp3', part:'noun', definition:"a powerful motor-driven vehicle with large, heavy treads, used for pulling farm machinery, other vehicles, etc.")
Word.find_or_initialize_by(word:'garlic').update(audio_url:'G00/G0054400.mp3', part:'noun', definition:"a hardy plant, Allium sativum, of the amaryllis family whose strongly, pungent bulb is used in cookery and medicine.")
Word.find_or_initialize_by(word:'likable').update(audio_url:'L02/L0252200.mp3', part:'adjective', definition:"readily or easily liked; pleasing: a likable young man.")
Word.find_or_initialize_by(word:'hinge').update(audio_url:'H02/H0291800.mp3', part:'noun', definition:"a jointed device or flexible piece on which a door, gate, shutter, lid, or other attached part turns, swings, or moves.")
Word.find_or_initialize_by(word:'future').update(audio_url:'F04/F0434600.mp3', part:'noun', definition:"time that is to be or come hereafter.")
Word.find_or_initialize_by(word:'gusto').update(audio_url:'G04/G0411200.mp3', part:'noun', definition:"hearty or keen enjoyment, as in eating or drinking, or in action or speech in general: to dance with gusto.")
Word.find_or_initialize_by(word:"o'clock").update(audio_url:'O00/O0031600.mp3', part:'adverb', definition:"of, by, or according to the clock (used in specifying the hour of the day): It is now 4 o'clock.")
Word.find_or_initialize_by(word:'upshot').update(audio_url:'U01/U0148500.mp3', part:'noun', definition:"the final issue, the conclusion, or the result: The upshot of the disagreement was a new bylaw.")
Word.find_or_initialize_by(word:'barter').update(audio_url:'B01/B0123900.mp3', part:'verb (used without object)', definition:"to trade by exchange of commodities rather than by the use of money.")
Word.find_or_initialize_by(word:'hefty').update(audio_url:'H01/H0159800.mp3', part:'adjective', definition:"heavy; weighty: a hefty book.")
Word.find_or_initialize_by(word:'glimmer').update(audio_url:'G01/G0189300.mp3', part:'noun', definition:"a faint or unsteady light; gleam.")
Word.find_or_initialize_by(word:'jackpot').update(audio_url:'J00/J0005900.mp3', part:'noun', definition:"the chief prize or the cumulative stakes in a game or contest, as in bingo, a quiz contest, or a slot machine.")
Word.find_or_initialize_by(word:'plaza').update(audio_url:'P05/P0537300.mp3', part:'noun', definition:"a public square or open space in a city or town.")
Word.find_or_initialize_by(word:'naysayer').update(audio_url:'N00/N0046900.mp3', part:'noun', definition:"a person who habitually expresses negative or pessimistic views: Despite a general feeling that things were going well, a few naysayers tried to cast gloom.")
Word.find_or_initialize_by(word:'around').update(audio_url:'A06/A0693200.mp3', part:'adverb', definition:"in a circle, ring, or the like; so as to surround a person, group, thing, etc.: The crowd gathered around.")
Word.find_or_initialize_by(word:'splendid').update(audio_url:'S08/S0823800.mp3', part:'adjective', definition:"gorgeous; magnificent; sumptuous. Synonyms: luxurious, dazzling, imposing.")
Word.find_or_initialize_by(word:'zinger').update(audio_url:'Z00/Z0028900.mp3', part:'noun', definition:"a quick, witty, or pointed remark or retort: During the debate she made a couple of zingers that deflated the opposition.")
Word.find_or_initialize_by(word:'band-aid').update(audio_url:'B00/B0072100.mp3', part:'noun', definition:"a brand of adhesive bandage with a gauze pad in the center, used to cover minor abrasions and cuts.")
Word.find_or_initialize_by(word:'watchdog').update(audio_url:'W00/W0052400.mp3', part:'noun', definition:"a dog kept to guard property.")
Word.find_or_initialize_by(word:'dearly').update(audio_url:'D00/D0069700.mp3', part:'adjective', definition:"beloved or loved: a dear friend.")
Word.find_or_initialize_by(word:'impostor').update(audio_url:'I00/I0082500.mp3', part:'noun', definition:"a person who practices deception under an assumed character, identity, or name.")
Word.find_or_initialize_by(word:'tirade').update(audio_url:'T03/T0320100.mp3', part:'noun', definition:"a prolonged outburst of bitter, outspoken denunciation: a tirade against smoking.")
Word.find_or_initialize_by(word:'drench').update(audio_url:'D05/D0526600.mp3', part:'verb (used with object)', definition:"to wet thoroughly; soak.")
Word.find_or_initialize_by(word:'buoyancy').update(audio_url:'B07/B0703700.mp3', part:'noun', definition:"the power to float or rise in a fluid; relative lightness.")
Word.find_or_initialize_by(word:'bonkers').update(audio_url:'B04/B0488000.mp3', part:'adjective', definition:"mentally unbalanced; mad; crazy.")
Word.find_or_initialize_by(word:'seldom').update(audio_url:'S02/S0280100.mp3', part:'adverb', definition:"on only a few occasions; rarely; infrequently; not often: We seldom see our old neighbors anymore.")
Word.find_or_initialize_by(word:'calico').update(audio_url:'C00/C0046600.mp3', part:'noun', definition:"a plain-woven cotton cloth printed with a figured pattern, usually on one side.")
Word.find_or_initialize_by(word:'postpone').update(audio_url:'P06/P0677200.mp3', part:'verb (used with object)', definition:"to put off to a later time; defer: He has postponed his departure until tomorrow.")
Word.find_or_initialize_by(word:'coward').update(audio_url:'C09/C0930400.mp3', part:'noun', definition:"a person who lacks courage in facing danger, difficulty, opposition, pain, etc.; a timid or easily intimidated person.")
Word.find_or_initialize_by(word:'error').update(audio_url:'E02/E0284800.mp3', part:'noun', definition:"a deviation from accuracy or correctness; a mistake, as in action or speech: His speech contained several factual errors.")
Word.find_or_initialize_by(word:'owlishly').update(audio_url:'O02/O0271300.mp3', part:'adjective', definition:"resembling or characteristic of an owl: His thick glasses give him an owlish appearance.")
Word.find_or_initialize_by(word:'barrel').update(audio_url:'B01/B0118100.mp3', part:'noun', definition:"a cylindrical wooden container with slightly bulging sides made of staves hooped together, and with flat, parallel ends.")
Word.find_or_initialize_by(word:'beagle').update(audio_url:'B01/B0174300.mp3', part:'noun', definition:"one of a breed of small hounds having long ears, short legs, and a usually black, tan, and white coat.")
Word.find_or_initialize_by(word:'bawl').update(audio_url:'B01/B0165700.mp3', part:'verb (used without object)', definition:"to cry or wail lustily.")
Word.find_or_initialize_by(word:'tomorrow').update(audio_url:'T03/T0357600.mp3', part:'noun', definition:"the day following today: Tomorrow is supposed to be sunny.")
Word.find_or_initialize_by(word:'crumb').update(audio_url:'C10/C1011200.mp3', part:'noun', definition:"a small particle of bread, cake, etc., that has broken off.")
Word.find_or_initialize_by(word:'dough').update(audio_url:'D04/D0491400.mp3', part:'noun', definition:"flour or meal combined with water, milk, etc., in a mass for baking into bread, cake, etc.; paste of bread.")
Word.find_or_initialize_by(word:'rattler').update(audio_url:'R00/R0078600.mp3', part:'noun', definition:"a rattlesnake.")
Word.find_or_initialize_by(word:'medley').update(audio_url:'M02/M0260600.mp3', part:'noun', definition:"a mixture, especially of heterogeneous elements; hodgepodge; jumble.")
Word.find_or_initialize_by(word:'difficult').update(audio_url:'D02/D0295400.mp3', part:'adjective', definition:"not easily or readily done; requiring much labor, skill, or planning to be performed successfully; hard: a difficult job.")
Word.find_or_initialize_by(word:'fringe').update(audio_url:'F03/F0379100.mp3', part:'noun', definition:"a decorative border of thread, cord, or the like, usually hanging loosely from a raveled edge or separate strip.")
Word.find_or_initialize_by(word:'casserole').update(audio_url:'C01/C0192200.mp3', part:'noun', definition:"a baking dish of glass, pottery, etc., usually with a cover.")
Word.find_or_initialize_by(word:'platinum').update(audio_url:'P05/P0529100.mp3', part:'noun', definition:"Chemistry. a heavy, grayish-white, highly malleable and ductile metallic element, resistant to most chemicals, practically unoxidizable except in the presence of bases, and fusible only at extremely high temperatures: used for making chemical and scientific apparatus, as a catalyst in the oxidation of ammonia to nitric acid, and in jewelry. Symbol:  Pt; atomic weight:  195.09; atomic number:  78; specific gravity:  21.5 at 20&#176;C.")
Word.find_or_initialize_by(word:'mundane').update(audio_url:'M06/M0687000.mp3', part:'adjective', definition:"common; ordinary; banal; unimaginative.")
Word.find_or_initialize_by(word:'alpaca').update(audio_url:'A03/A0346700.mp3', part:'noun', definition:"a domesticated South American ruminant, Lama pacos, having long, soft, silky fleece, related to the llama and believed to be a variety of the guanaco.")
Word.find_or_initialize_by(word:'billiards').update(audio_url:'B03/B0331100.mp3', part:'noun', definition:"any of several games played with hard balls of ivory or of a similar material that are driven with a cue on a cloth-covered table enclosed by a raised rim of rubber, especially a game played with a cue ball and two object balls on a table without pockets.")
Word.find_or_initialize_by(word:'cyclone').update(audio_url:'C10/C1087200.mp3', part:'noun', definition:"a large-scale, atmospheric wind-and-pressure system characterized by low pressure at its center and by circular wind motion, counterclockwise in the Northern Hemisphere, clockwise in the Southern Hemisphere.")
Word.find_or_initialize_by(word:'scrooge').update(audio_url:'S02/S0228200.mp3', part:'verb (used with or without object)', definition:"scrouge.")
Word.find_or_initialize_by(word:'genteel').update(audio_url:'G01/G0106000.mp3', part:'adjective', definition:"belonging or suited to polite society.")
Word.find_or_initialize_by(word:'collude').update(audio_url:'C06/C0651400.mp3', part:'verb (used without object)', definition:"to act together through a secret understanding, especially with evil or harmful intent.")
Word.find_or_initialize_by(word:'guardian').update(audio_url:'G03/G0381500.mp3', part:'noun', definition:"a person who guards, protects, or preserves.")
Word.find_or_initialize_by(word:'mosaic').update(audio_url:'M06/M0624500.mp3', part:'noun', definition:"a picture or decoration made of small, usually colored pieces of inlaid stone, glass, etc.")
Word.find_or_initialize_by(word:'enunciate').update(audio_url:'E02/E0221600.mp3', part:'verb (used with object)', definition:"to utter or pronounce (words, sentences, etc.) especially in an articulate or a particular manner: He enunciates his words distinctly.")
Word.find_or_initialize_by(word:'melodramatic').update(audio_url:'M02/M0287400.mp3', part:'adjective', definition:"of, like, or befitting melodrama.")
Word.find_or_initialize_by(word:'epoxy').update(audio_url:'E02/E0259600.mp3', part:'adjective', definition:"having the structure of an epoxide.")
Word.find_or_initialize_by(word:'chortle').update(audio_url:'C04/C0448200.mp3', part:'verb (used without object)', definition:"to chuckle gleefully.")
Word.find_or_initialize_by(word:'yurt').update(audio_url:'Y00/Y0052200.mp3', part:'noun', definition:"a tentlike dwelling of the Mongol and Turkic peoples of central Asia, consisting of a cylindrical wall of poles in a lattice arrangement with a conical roof of poles, both covered by felt or skins.")
Word.find_or_initialize_by(word:'wysiwyg').update(audio_url:'W02/W0262600.mp3', part:'adjective', definition:"of, relating to, or noting a screen display that shows text exactly as it will appear in printed output, including underlining, various typefaces, as italics, line spacing, end-of-line breaks, and paragraph indentations.")
Word.find_or_initialize_by(word:'banquet').update(audio_url:'B00/B0084900.mp3', part:'noun', definition:"a lavish meal; feast.")
Word.find_or_initialize_by(word:'escarpment').update(audio_url:'E02/E0294100.mp3', part:'noun', definition:"Geology. a long, precipitous, clifflike ridge of land, rock, or the like, commonly formed by faulting or fracturing of the earth's crust.")
Word.find_or_initialize_by(word:'zealous').update(audio_url:'Z00/Z0010800.mp3', part:'adjective', definition:"full of, characterized by, or due to zeal; ardently active, devoted, or diligent. Synonyms: enthusiastic, eager, fervid, fervent, intense, passionate, warm.")
Word.find_or_initialize_by(word:'decor').update(audio_url:'D00/D0099700.mp3', part:'noun', definition:"style or mode of decoration, as of a room, building, or the like: modern office d&#233;cor; a bedroom having a Spanish d&#233;cor.")
Word.find_or_initialize_by(word:'revelation').update(audio_url:'R02/R0262500.mp3', part:'noun', definition:"the act of revealing or disclosing; disclosure.")
Word.find_or_initialize_by(word:'vague').update(audio_url:'V00/V0007300.mp3', part:'adjective', definition:"not clearly or explicitly stated or expressed: vague promises.")
Word.find_or_initialize_by(word:'cumulus').update(audio_url:'C10/C1045200.mp3', part:'noun', definition:"a heap; pile.")
Word.find_or_initialize_by(word:'montage').update(audio_url:'M05/M0584800.mp3', part:'noun', definition:"the technique of combining in a single composition pictorial elements from various sources, as parts of different photographs or fragments of printing, either to give the illusion that the elements belonged together originally or to allow each element to retain its separate identity as a means of adding interest or meaning to the composition.")
Word.find_or_initialize_by(word:'query').update(audio_url:'Q00/Q0033800.mp3', part:'noun', definition:"a question; an inquiry.")
Word.find_or_initialize_by(word:'maximum').update(audio_url:'M02/M0224900.mp3', part:'noun', definition:"the greatest quantity or amount possible, assignable, allowable, etc.")
Word.find_or_initialize_by(word:'territory').update(audio_url:'T01/T0166900.mp3', part:'noun', definition:"any tract of land; region or district.")
Word.find_or_initialize_by(word:'nationalism').update(audio_url:'N00/N0037800.mp3', part:'noun', definition:"spirit or aspirations common to the whole of a nation.")
Word.find_or_initialize_by(word:'latency').update(audio_url:'L00/L0099800.mp3', part:'noun', definition:"the state of being latent.")
Word.find_or_initialize_by(word:'bat').update(audio_url:'B01/B0147400.mp3', part:'noun', definition:"Sports. the wooden club used in certain games, as baseball and cricket, to strike the ball.")
Word.find_or_initialize_by(word:'sock').update(audio_url:'S06/S0683800.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'yam').update(audio_url:'Y00/Y0005400.mp3', part:'noun', definition:"the starchy, tuberous root of any of various climbing vines of the genus Dioscorea, cultivated for food in warm regions.")
Word.find_or_initialize_by(word:'peep').update(audio_url:'P02/P0213600.mp3', part:'verb (used without object)', definition:"")
Word.find_or_initialize_by(word:'candy').update(audio_url:'C00/C0089200.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'pull').update(audio_url:'P09/P0920200.mp3', part:'verb (used with object)', definition:"to draw or haul toward oneself or itself, in a particular direction, or into a particular position: to pull a sled up a hill.")
Word.find_or_initialize_by(word:'synthetic').update(audio_url:'S12/S1227000.mp3', part:'adjective', definition:"of, pertaining to, proceeding by, or involving synthesis (opposed to analytic).")
Word.find_or_initialize_by(word:'caftan').update(audio_url:'C00/C0026100.mp3', part:'noun', definition:"a long garment having long sleeves and tied at the waist by a girdle, worn under a coat in the Middle East.")
Word.find_or_initialize_by(word:'resume').update(audio_url:'R02/R0240300.mp3', part:'verb (used with object)', definition:"to take up or go on with again after interruption; continue: to resume a journey.")
Word.find_or_initialize_by(word:'cylindrical').update(audio_url:'C10/C1092000.mp3', part:'adjective', definition:"of, relating to, or having the form of a cylinder.")
Word.find_or_initialize_by(word:'hubris').update(audio_url:'H04/H0420800.mp3', part:'noun', definition:"excessive pride or self-confidence; arrogance.")
Word.find_or_initialize_by(word:'pathogen').update(audio_url:'P01/P0166300.mp3', part:'noun', definition:"any disease-producing agent, especially a virus, bacterium, or other microorganism.")
Word.find_or_initialize_by(word:'carnitas').update(audio_url:'C01/C0159800.mp3', part:'plural noun', definition:"small or shredded pieces of crisp roast pork, eaten as a snack, used as a filling for burritos, etc.")
Word.find_or_initialize_by(word:'stagflation').update(audio_url:'S08/S0872400.mp3', part:'noun', definition:"an inflationary period accompanied by rising unemployment and lack of growth in consumer demand and business activity.")
Word.find_or_initialize_by(word:'esoteric').update(audio_url:'E03/E0300300.mp3', part:'adjective', definition:"understood by or meant for only the select few who have special knowledge or interest; recondite: poetry full of esoteric allusions.")
Word.find_or_initialize_by(word:'bark').update(audio_url:'B01/B0104500.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'melt').update(audio_url:'M02/M0288600.mp3', part:'verb (used without object)', definition:"")
Word.find_or_initialize_by(word:'sky').update(audio_url:'S05/S0599600.mp3', part:'noun', definition:"the region of the clouds or the upper air; the upper atmosphere of the earth: airplanes in the sky; cloudy skies.")
Word.find_or_initialize_by(word:'lucky').update(audio_url:'L04/L0412400.mp3', part:'adjective', definition:"having or marked by good luck; fortunate: That was my lucky day.")
Word.find_or_initialize_by(word:'smug').update(audio_url:'S06/S0653000.mp3', part:'adjective', definition:"")
Word.find_or_initialize_by(word:'vote').update(audio_url:'V01/V0193000.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'truck').update(audio_url:'T05/T0536300.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'blob').update(audio_url:'B04/B0417600.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'tank').update(audio_url:'T00/T0051500.mp3', part:'noun', definition:"a large receptacle, container, or structure for holding a liquid or gas: tanks for storing oil.")
Word.find_or_initialize_by(word:'napkin').update(audio_url:'N00/N0022900.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'good').update(audio_url:'G02/G0255000.mp3', part:'adjective', definition:"morally excellent; virtuous; righteous; pious: a good man.")
Word.find_or_initialize_by(word:'dress').update(audio_url:'D05/D0526900.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'store').update(audio_url:'NEW/NEW14805.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'apart').update(audio_url:'A05/A0580200.mp3', part:'adverb', definition:"into pieces or parts; to pieces: to take a watch apart; an old barn falling apart from decay.")
Word.find_or_initialize_by(word:'thing').update(audio_url:'T02/T0234300.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'all-star').update(audio_url:'A03/A0336100.mp3', part:'adjective', definition:"consisting of athletes chosen as the best at their positions from all teams in a league or region: Our quarterback was chosen for the all-star team.")
Word.find_or_initialize_by(word:'approximate').update(audio_url:'A06/A0619000.mp3', part:'adjective', definition:"near or approaching a certain state, condition, goal, or standard.")
Word.find_or_initialize_by(word:'pinnacle').update(audio_url:'P04/P0469100.mp3', part:'noun', definition:"a lofty peak.")
Word.find_or_initialize_by(word:'molasses').update(audio_url:'M05/M0533600.mp3', part:'noun', definition:"a thick syrup produced during the refining of sugar or from sorghum, varying from light to dark brown in color.")
Word.find_or_initialize_by(word:'contentious').update(audio_url:'C07/C0791700.mp3', part:'adjective', definition:"tending to argument or strife; quarrelsome: a contentious crew.")
Word.find_or_initialize_by(word:'acoustic').update(audio_url:'A00/A0092900.mp3', part:'adjective', definition:"pertaining to the sense or organs of hearing, to sound, or to the science of sound.")
Word.find_or_initialize_by(word:'supine').update(audio_url:'S11/S1143100.mp3', part:'adjective', definition:"lying on the back, face or front upward.")
Word.find_or_initialize_by(word:'tenement').update(audio_url:'T01/T0140700.mp3', part:'noun', definition:"Also called tenement house. a run-down and often overcrowded apartment house, especially in a poor section of a large city.")
Word.find_or_initialize_by(word:'philarmonic').update(audio_url:'P03/P0359400.mp3', part:'', definition:"")
Word.find_or_initialize_by(word:'quid pro quo').update(audio_url:'Q00/Q0039400.mp3', part:'noun', definition:"(italics) Latin. one thing in return for another.")
Word.find_or_initialize_by(word:'iambic').update(audio_url:'I00/I0000600.mp3', part:'adjective', definition:"Prosody.")
Word.find_or_initialize_by(word:'legislature').update(audio_url:'L01/L0160800.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'spectacles').update(audio_url:'S07/S0778200.mp3', part:'noun', definition:"anything presented to the sight or view, especially something of a striking or impressive kind: The stars make a fine spectacle tonight.")
Word.find_or_initialize_by(word:'methodology').update(audio_url:'M03/M0364800.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'umbrage').update(audio_url:'U00/U0021600.mp3', part:'noun', definition:"offense; annoyance; displeasure: to feel umbrage at a social snub; to give umbrage to someone; to take umbrage at someone's rudeness.")
Word.find_or_initialize_by(word:'diametrically').update(audio_url:'D02/D0262400.mp3', part:'adjective', definition:"of, relating to, or along a diameter.")
Word.find_or_initialize_by(word:'commandeer').update(audio_url:'C06/C0678800.mp3', part:'verb (used with object)', definition:"")
Word.find_or_initialize_by(word:'proprietary').update(audio_url:'P08/P0839400.mp3', part:'adjective', definition:"belonging to a proprietor.")
Word.find_or_initialize_by(word:'celsius').update(audio_url:'C02/C0254800.mp3', part:'noun', definition:"Anders prontoggle pronounce-inline, Swedish astronomer who devised the Celsius temperature scale.")
Word.find_or_initialize_by(word:'migraine').update(audio_url:'M04/M0424600.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'cartouches').update(audio_url:'C01/C0179300.mp3', part:'noun', definition:"Architecture. a rounded, convex surface, usually surrounded with carved ornamental scrollwork, for receiving a painted or low-relief decoration, as an escutcheon.")
Word.find_or_initialize_by(word:'resilience').update(audio_url:'R02/R0226500.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'braille').update(audio_url:'B05/B0571700.mp3', part:'noun', definition:"French teacher of the blind.")
Word.find_or_initialize_by(word:'gibbous').update(audio_url:'G01/G0142800.mp3', part:'adjective', definition:"Astronomy. (of a heavenly body) convex at both edges, as the moon when more than half full.")
Word.find_or_initialize_by(word:'germane').update(audio_url:'G01/G0123900.mp3', part:'adjective', definition:"closely or significantly related; relevant; pertinent: Please keep your statements germane to the issue.")
Word.find_or_initialize_by(word:'augment').update(audio_url:'A08/A0807800.mp3', part:'verb (used with object)', definition:"to make larger; enlarge in size, number, strength, or extent; increase: His salary is augmented by a small inheritance.")
Word.find_or_initialize_by(word:'sustainable').update(audio_url:'NEW2014/4417583.mp3', part:'adjective', definition:"capable of being supported or upheld, as by having its weight borne from below.")
Word.find_or_initialize_by(word:'serpentine').update(audio_url:'S03/S0365300.mp3', part:'adjective', definition:"of, characteristic of, or resembling a serpent, as in form or movement.")
Word.find_or_initialize_by(word:'jurisdiction').update(audio_url:'J01/J0120000.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'languish').update(audio_url:'L00/L0069200.mp3', part:'verb (used without object)', definition:"")
Word.find_or_initialize_by(word:'acetone').update(audio_url:'A00/A0073000.mp3', part:'noun', definition:"a colorless, volatile, water-soluble, flammable liquid, C <sub>3</sub> H <sub>6</sub> O, usually derived by oxidation of isopropyl alcohol or by bacterial fermentation of carbohydrates: used chiefly in paints and varnishes, as a general solvent, and in organic synthesis.")
Word.find_or_initialize_by(word:'plaintiff').update(audio_url:'P05/P0510200.mp3', part:'noun', definition:"a person who brings suit in a court (opposed to defendant).")
Word.find_or_initialize_by(word:'reciprocate').update(audio_url:'R01/R0109000.mp3', part:'verb (used with object)', definition:"")
Word.find_or_initialize_by(word:'laceration').update(audio_url:'L00/L0010100.mp3', part:'noun', definition:"the result of lacerating; a rough, jagged tear.")
Word.find_or_initialize_by(word:'inclement').update(audio_url:'I01/I0105300.mp3', part:'adjective', definition:"")
Word.find_or_initialize_by(word:'generosity').update(audio_url:'G00/G0098000.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'arboreal').update(audio_url:'A06/A0642000.mp3', part:'adjective', definition:"")
Word.find_or_initialize_by(word:'ramifications').update(audio_url:'R00/R0048800.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'excursion').update(audio_url:'E03/E0386500.mp3', part:'noun', definition:"a short trip or outing to some place, usually for a special purpose and with the intention of a prompt return: a pleasure excursion; a scientific excursion.")
Word.find_or_initialize_by(word:'olfactory').update(audio_url:'O00/O0080900.mp3', part:'adjective', definition:"of or relating to the sense of smell: olfactory organs.")
Word.find_or_initialize_by(word:'adhesion').update(audio_url:'A01/A0129700.mp3', part:'noun', definition:"the act or state of adhering; state of being adhered or united: the adhesion of parts united by growth.")
Word.find_or_initialize_by(word:'par excellence').update(audio_url:'P01/P0116800.mp3', part:'adjective', definition:"being an example of excellence; superior; preeminent: a chef par excellence.")
Word.find_or_initialize_by(word:'shoji').update(audio_url:'S04/S0464900.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'ostensibly').update(audio_url:'O01/O0192200.mp3', part:'adjective', definition:"outwardly appearing as such; professed; pretended: an ostensible cheerfulness concealing sadness.")
Word.find_or_initialize_by(word:'appositive').update(audio_url:'A06/A0615300.mp3', part:'noun', definition:"a word or phrase in apposition.")
Word.find_or_initialize_by(word:'soiree').update(audio_url:'S06/S0694300.mp3', part:'noun', definition:"an evening party or social gathering, especially one held for a particular purpose: a musical soiree.")
Word.find_or_initialize_by(word:'effusive').update(audio_url:'E00/E0056900.mp3', part:'adjective', definition:"unduly demonstrative; lacking reserve: effusive greetings; an effusive person.")
Word.find_or_initialize_by(word:'impervious').update(audio_url:'I00/I0076100.mp3', part:'adjective', definition:"not permitting penetration or passage; impenetrable: The coat is impervious to rain.")
Word.find_or_initialize_by(word:'sanskrit').update(audio_url:'S00/S0085300.mp3', part:'noun', definition:"an Indo-European, Indic language, in use since c1200 b.c. as the religious and classical literary language of India. Abbreviation:  Skt.")
Word.find_or_initialize_by(word:'espadrille').update(audio_url:'E03/E0301000.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'patrician').update(audio_url:'P01/P0171300.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'tarmac').update(audio_url:'T00/T0067900.mp3', part:'noun', definition:"a brand of bituminous binder, similar to tarmacadam, for surfacing roads, airport runways, parking areas, etc.")
Word.find_or_initialize_by(word:'estuary').update(audio_url:'E03/E0316400.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'frigate').update(audio_url:'F03/F0376800.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'commodious').update(audio_url:'C06/C0686300.mp3', part:'adjective', definition:"spacious and convenient; roomy: a commodious apartment.")
Word.find_or_initialize_by(word:'machination').update(audio_url:'M00/M0009800.mp3', part:'noun', definition:"an act or instance of machinating.")
Word.find_or_initialize_by(word:'quasar').update(audio_url:'Q00/Q0024800.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'corollary').update(audio_url:'C08/C0860100.mp3', part:'noun', definition:"Mathematics. a proposition that is incidentally proved in proving another proposition.")
Word.find_or_initialize_by(word:'inimical').update(audio_url:'I01/I0180100.mp3', part:'adjective', definition:"adverse in tendency or effect; unfavorable; harmful: a climate inimical to health.")
Word.find_or_initialize_by(word:'garrulous').update(audio_url:'G00/G0057600.mp3', part:'adjective', definition:"")
Word.find_or_initialize_by(word:'tarantula').update(audio_url:'T00/T0064000.mp3', part:'noun', definition:"any of several large, hairy spiders of the family Theraphosidae, as Aphonopelma chalcodes, of the southwestern U.S., having a painful but not highly venomous bite.")
Word.find_or_initialize_by(word:'mazel tov').update(audio_url:'M02/M0232500.mp3', part:'noun', definition:"an expression of congratulations and best wishes, used chiefly by Jews: A chorus of mazel tovs greeted the newlyweds as they circulated from table to table.")
Word.find_or_initialize_by(word:'esplanade').update(audio_url:'E03/E0302800.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'smorgasbord').update(audio_url:'S06/S0652000.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'mawkish').update(audio_url:'M02/M0222900.mp3', part:'adjective', definition:"")
Word.find_or_initialize_by(word:'temerity').update(audio_url:'T01/T0130700.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'nascent').update(audio_url:'N00/N0032200.mp3', part:'adjective', definition:"beginning to exist or develop: That nascent republic is holding its first election this month.")
Word.find_or_initialize_by(word:'phoenix').update(audio_url:'P03/P0370400.mp3', part:'noun', definition:"(sometimes initial capital letter) a mythical bird of great beauty fabled to live 500 or 600 years in the Arabian wilderness, to burn itself on a funeral pyre, and to rise from its ashes in the freshness of youth and live through another cycle of years: often an emblem of immortality or of reborn idealism or hope.")
Word.find_or_initialize_by(word:'buoyancy').update(audio_url:'B07/B0703700.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'melee').update(audio_url:'M02/M0281400.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'ciao').update(audio_url:'C04/C0481700.mp3', part:'interjection', definition:"")
Word.find_or_initialize_by(word:'schnitzel').update(audio_url:'S01/S0179900.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'porcelain').update(audio_url:'P06/P0648500.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'evanescent').update(audio_url:'E03/E0357200.mp3', part:'adjective', definition:"")
Word.find_or_initialize_by(word:'acquiesce').update(audio_url:'A00/A0093900.mp3', part:'verb (used without object)', definition:"to assent tacitly; submit or comply silently or without protest; agree; consent: to acquiesce halfheartedly in a business plan.")
Word.find_or_initialize_by(word:'pharaoh').update(audio_url:'P03/P0340900.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'alfresco').update(audio_url:'A02/A0298700.mp3', part:'adverb', definition:"out-of-doors; in the open air: to dine alfresco.")
Word.find_or_initialize_by(word:'gossamer').update(audio_url:'G02/G0271000.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'deciduous').update(audio_url:'D00/D0090500.mp3', part:'adjective', definition:"")
Word.find_or_initialize_by(word:'nanotechnology').update(audio_url:'N00/N0018500.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'basilica').update(audio_url:'B01/B0135800.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'solstice').update(audio_url:'S07/S0708000.mp3', part:'noun', definition:"Astronomy. either of the two times a year when the sun is at its greatest distance from the celestial equator: about June 21, when the sun reaches its northernmost point on the celestial sphere, or about December 22, when it reaches its southernmost point. Compare summer solstice, winter solstice. either of the two points in the ecliptic farthest from the equator.")
Word.find_or_initialize_by(word:'conglomerate').update(audio_url:'C07/C0752800.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'turpitude').update(audio_url:'T05/T0586400.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'fungible').update(audio_url:'F04/F0419500.mp3', part:'adjective', definition:"")
Word.find_or_initialize_by(word:'desertification').update(audio_url:'D02/D0211800.mp3', part:'noun', definition:"the processes by which an area becomes a desert.")
Word.find_or_initialize_by(word:'anemone').update(audio_url:'A04/A0466200.mp3', part:'noun', definition:"any of various plants belonging to the genus Anemone, of the buttercup family, having petallike sepals and including several wild species with white flowers as well as others cultivated for their showy flowers in a variety of colors.")
Word.find_or_initialize_by(word:'oubliette').update(audio_url:'O02/O0207700.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'gargantuan').update(audio_url:'G00/G0053200.mp3', part:'adjective', definition:"gigantic; enormous; colossal: a gargantuan task.")
Word.find_or_initialize_by(word:'corsair').update(audio_url:'C08/C0873100.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'idiosyncratic').update(audio_url:'I00/I0023500.mp3', part:'adjective', definition:"pertaining to the nature of idiosyncrasy, or something peculiar to an individual: The best minds are idiosyncratic and unpredictable as they follow the course of scientific discovery.")
Word.find_or_initialize_by(word:'vituperative').update(audio_url:'V01/V0167500.mp3', part:'adjective', definition:"characterized by or of the nature of vituperation: vituperative remarks.")
Word.find_or_initialize_by(word:'orwellian').update(audio_url:'O01/O0179900.mp3', part:'adjective', definition:"of, pertaining to, characteristic of, or resembling the literary work of George Orwell or the totalitarian future described in his antiutopian novel 1984 (1949).")
Word.find_or_initialize_by(word:'bossa nova').update(audio_url:'B05/B0522000.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'pachyderm').update(audio_url:'P00/P0004000.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'vainglorious').update(audio_url:'V00/V0008100.mp3', part:'adjective', definition:"filled with or given to vainglory: a vainglorious actor.")
Word.find_or_initialize_by(word:'hegemony').update(audio_url:'H01/H0160600.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'echelon').update(audio_url:'E00/E0023000.mp3', part:'noun', definition:"a level of command, authority, or rank: After years of service, she is now in the upper echelon of city officials.")
Word.find_or_initialize_by(word:'larynx').update(audio_url:'L00/L0092500.mp3', part:'noun', definition:"Anatomy. a muscular and cartilaginous structure lined with mucous membrane at the upper part of the trachea in humans, in which the vocal cords are located.")
Word.find_or_initialize_by(word:'concatenate').update(audio_url:'C07/C0717100.mp3', part:'verb (used with object)', definition:"")
Word.find_or_initialize_by(word:'arpeggio').update(audio_url:'A06/A0694200.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'gemini').update(audio_url:'G00/G0091100.mp3', part:'plural noun', definition:"Astronomy. the Twins, a zodiacal constellation between Taurus and Cancer containing the bright stars Castor and Pollux.")
Word.find_or_initialize_by(word:'obelisk').update(audio_url:'O00/O0005400.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'sanctimonious').update(audio_url:'S00/S0066900.mp3', part:'adjective', definition:"making a hypocritical show of religious devotion, piety, righteousness, etc.: They resented his sanctimonious comments on immorality in America.")
Word.find_or_initialize_by(word:'force majeure').update(audio_url:'F02/F0281000.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'tungsten').update(audio_url:'T05/T0570500.mp3', part:'noun', definition:"a rare, metallic element having a bright-gray color, a metallic luster, and a high melting point, 3410&#176; C, and found in wolframite, tungstite, and other minerals: used in alloys of high-speed cutting tools, electric-lamp filaments, etc. Symbol:  W; atomic weight:  183.85; atomic number:  74; specific gravity:  19.3.")
Word.find_or_initialize_by(word:'auriferous').update(audio_url:'A08/A0815200.mp3', part:'adjective', definition:"")
Word.find_or_initialize_by(word:'pulcritude').update(audio_url:'P09/P0919200.mp3', part:'', definition:"")
Word.find_or_initialize_by(word:'de rigueur').update(audio_url:'D02/D0200100.mp3', part:'adjective', definition:"")
Word.find_or_initialize_by(word:'nunchaku').update(audio_url:'N02/N0264600.mp3', part:'noun', definition:"Sometimes, nunchakus. a Japanese hand weapon for defense against frontal assault, consisting of two foot-long hardwood sticks joined by a chain or thick cord that stretches to body width.")
Word.find_or_initialize_by(word:'guttural').update(audio_url:'G04/G0413700.mp3', part:'adjective', definition:"")
Word.find_or_initialize_by(word:'interlocutor').update(audio_url:'I02/I0241800.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'joule').update(audio_url:'J00/J0094600.mp3', part:'noun', definition:"the standard unit of work or energy in the International System of Units (SI) equal to the work done by a force of one newton when its point of application moves through a distance of one meter in the direction of the force: equivalent to 10 <sup>7</sup> ergs and one watt-second. Abbreviation:  J, j.")
Word.find_or_initialize_by(word:'freesia').update(audio_url:'F03/F0360800.mp3', part:'noun', definition:"any of several plants belonging to the genus Freesia, of the iris family, native to southern Africa, having fragrant white, yellow, or sometimes rose-colored, tubular flowers.")
Word.find_or_initialize_by(word:'susurration').update(audio_url:'S11/S1167000.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'potpourri').update(audio_url:'P06/P0687100.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'leitmotif').update(audio_url:'L01/L0168400.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'chihuahua').update(audio_url:'C03/C0395500.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'ecclesiastical').update(audio_url:'E00/E0020600.mp3', part:'adjective', definition:"")
Word.find_or_initialize_by(word:'cozen').update(audio_url:'C09/C0936800.mp3', part:'verb (used with or without object)', definition:"")
Word.find_or_initialize_by(word:'insouciance').update(audio_url:'I02/I0206800.mp3', part:'noun', definition:"the quality of being insouciant; lack of care or concern; indifference.")
Word.find_or_initialize_by(word:'jai alai').update(audio_url:'J00/J0014800.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'desiccate').update(audio_url:'D02/D0213200.mp3', part:'verb (used with object)', definition:"")
Word.find_or_initialize_by(word:'Iroquois').update(audio_url:'I03/I0305400.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'cheongsam').update(audio_url:'C03/C0372900.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'tranquil').update(audio_url:'T04/T0431700.mp3', part:'adjective', definition:"free from commotion or tumult; peaceful; quiet; calm: a tranquil country place.")
Word.find_or_initialize_by(word:'hypnotic').update(audio_url:'H05/H0505900.mp3', part:'adjective', definition:"of or relating to hypnosis or hypnotism.")
Word.find_or_initialize_by(word:'five').update(audio_url:'F01/F0178800.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'jelly').update(audio_url:'J00/J0044100.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'tiger').update(audio_url:'T02/T0294300.mp3', part:'noun', definition:"a large, carnivorous, tawny-colored and black-striped feline, Panthera tigris, of Asia, ranging in several subspecies from India and the Malay Peninsula to Siberia: the entire species is endangered, with some subspecies thought to be extinct.")
Word.find_or_initialize_by(word:'fuzzy').update(audio_url:'F04/F0436300.mp3', part:'adjective', definition:"of the nature of or resembling fuzz: a soft, fuzzy material.")
Word.find_or_initialize_by(word:'trace').update(audio_url:'T04/T0415100.mp3', part:'noun', definition:"a surviving mark, sign, or evidence of the former existence, influence, or action of some agent or event; vestige: traces of an advanced civilization among the ruins.")
Word.find_or_initialize_by(word:'broom').update(audio_url:'B06/B0643700.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'frame').update(audio_url:'F03/F0340800.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'hidden').update(audio_url:'H02/H0266000.mp3', part:'adjective', definition:"concealed; obscure; covert: hidden meaning; hidden hostility.")
Word.find_or_initialize_by(word:'navy').update(audio_url:'N00/N0046100.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'glass').update(audio_url:'G01/G0179900.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'copycat').update(audio_url:'C08/C0835000.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'plus').update(audio_url:'P05/P0559800.mp3', part:'preposition', definition:"more by the addition of; increased by: ten plus two is twelve.")
Word.find_or_initialize_by(word:'down').update(audio_url:'D04/D0499100.mp3', part:'adverb', definition:"from higher to lower; in descending direction or order; toward, into, or in a lower position: to come down the ladder.")
Word.find_or_initialize_by(word:'goldfish').update(audio_url:'G02/G0240300.mp3', part:'noun', definition:"a small, usually yellow or orange fish, Carassius auratus, of the carp family, native to China, bred in many varieties and often kept in fishbowls and pools.")
Word.find_or_initialize_by(word:'cheese').update(audio_url:'C03/C0360600.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'problem').update(audio_url:'P07/P0797300.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'cranny').update(audio_url:'C09/C0949700.mp3', part:'noun', definition:"a small, narrow opening in a wall, rock, etc.; chink; crevice; fissure: They searched every nook and cranny for the missing ring.")
Word.find_or_initialize_by(word:'grandma').update(audio_url:'G02/G0298700.mp3', part:'noun', definition:"grandmother.")
Word.find_or_initialize_by(word:'patch').update(audio_url:'P01/P0161300.mp3', part:'noun', definition:"a small piece of material used to mend a tear or break, to cover a hole, or to strengthen a weak place: patches at the elbows of a sports jacket.")
Word.find_or_initialize_by(word:'erase').update(audio_url:'E02/E0268600.mp3', part:'verb (used with object)', definition:"")
Word.find_or_initialize_by(word:'tuba').update(audio_url:'T05/T0553800.mp3', part:'noun', definition:"Music. a valved, brass wind instrument having a low range.")
Word.find_or_initialize_by(word:'curly').update(audio_url:'C10/C1057700.mp3', part:'adjective', definition:"curling or tending to curl: curly blond hair.")
Word.find_or_initialize_by(word:'soup').update(audio_url:'S07/S0744300.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'towel').update(audio_url:'T04/T0406300.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'only').update(audio_url:'O01/O0107300.mp3', part:'adverb', definition:"without others or anything further; alone; solely; exclusively: This information is for your eyes only.")
Word.find_or_initialize_by(word:'sailor').update(audio_url:'S00/S0027000.mp3', part:'noun', definition:"a person whose occupation is sailing or navigation; mariner.")
Word.find_or_initialize_by(word:'blue').update(audio_url:'B04/B0431900.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'which').update(audio_url:'W01/W0127100.mp3', part:'pronoun', definition:"what one?: Which of these do you want? Which do you want?")
Word.find_or_initialize_by(word:'rare').update(audio_url:'R00/R0066100.mp3', part:'adjective', definition:"coming or occurring far apart in time; unusual; uncommon: a rare disease; His visits are rare occasions.")
Word.find_or_initialize_by(word:'pamper').update(audio_url:'P00/P0049100.mp3', part:'verb (used with object)', definition:"to treat or gratify with extreme or excessive indulgence, kindness, or care: to pamper a child; to pamper one's stomach.")
Word.find_or_initialize_by(word:'dojo').update(audio_url:'D04/D0441300.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'chair').update(audio_url:'C02/C0298100.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'forget').update(audio_url:'F02/F0298600.mp3', part:'verb (used with object)', definition:"to cease or fail to remember; be unable to recall: to forget someone's name.")
Word.find_or_initialize_by(word:'arch').update(audio_url:'A06/A0646900.mp3', part:'noun', definition:"Architecture. a curved masonry construction for spanning an opening, consisting of a number of wedgelike stones, bricks, or the like, set with the narrower side toward the opening in such a way that forces on the arch are transmitted as vertical or oblique stresses on either side of the opening.")
Word.find_or_initialize_by(word:'bedrock').update(audio_url:'B01/B0196900.mp3', part:'noun', definition:"Geology. unbroken solid rock, overlaid in most places by soil or rock fragments.")
Word.find_or_initialize_by(word:'satin').update(audio_url:'S01/S0119600.mp3', part:'noun', definition:"a fabric in a warp-effect or filling-effect satin weave, as acetate, rayon, nylon, or silk, often having a glossy face and a soft, slippery texture.")
Word.find_or_initialize_by(word:'dizzy').update(audio_url:'D04/D0418000.mp3', part:'adjective', definition:"")
Word.find_or_initialize_by(word:'solo').update(audio_url:'S07/S0706700.mp3', part:'noun', definition:"a musical composition or a passage or section in a musical composition written for performance by one singer or instrumentalist, with or without accompaniment: She sang a solo.")
Word.find_or_initialize_by(word:'cream').update(audio_url:'C09/C0956600.mp3', part:'noun', definition:"")
Word.find_or_initialize_by(word:'regular').update(audio_url:'R01/R0164600.mp3', part:'adjective', definition:"usual; normal; customary: to put something in its regular place.")
Word.find_or_initialize_by(word:'x-ray').update(audio_url:'X00/X0011500.mp3', part:'noun', definition:"Physics. Often, x-rays. a form of electromagnetic radiation, similar to light but of shorter wavelength and capable of penetrating solids and of ionizing gases.")
Word.find_or_initialize_by(word:'teacher').update(audio_url:'T00/T0093900.mp3', part:'noun', definition:"a person who teaches or instructs, especially as a profession; instructor.")
